# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1))     # activation='sigmoid' used generally with classification problems
                                            # activation='softmax' if more than 2 categories to predict
                                            # No activation for regression

## Part 3 - Training the ANN

### Compiling the ANN

In [14]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [15]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 20857.0645
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 243.8063
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 212.6662
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 181.0195
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 151.7659
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 126.6427
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 105.9505
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 90.1173
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 78.0608
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 69.5399
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 63.2488
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss: 

### Predicting the results of the Test set

In [16]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
# reshaping into n=len(y_pred) rows and 1 columns matrix here
# np.concatenate has two parameters as input first the elements in () then axis. Here vertical axis therefore 1

[[427.86 431.23]
 [458.86 460.01]
 [462.38 461.14]
 ...
 [469.56 473.26]
 [436.5  438.  ]
 [455.65 463.28]]


### Error

In [17]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

36.52393766610092